# Generated by Django 4.0.5 on 2022-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_archivos_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegaproductos',
            name='xvilla',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='solicitud',
            field=models.CharField(max_length=100),
        ),
    ]
