# Generated by Django 4.0.5 on 2022-08-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_bodegaproductos_xvilla_alter_archivos_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='inicial',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
