# Generated by Django 4.0.5 on 2022-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_recepcion_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegaproductos',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodegaproductos',
            name='categoria',
            field=models.CharField(choices=[('', 'ELIGE UNA OPCION'), ('1', 'EQUIPO'), ('2', 'MUEBLE'), ('3', 'ACCESORIO'), ('4', 'HERRERIA'), ('5', 'CANCELERIA'), ('6', 'CARPINTERIA'), ('7', 'ACABADO'), ('8', 'MATERIAL')], default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bodegaproductos',
            name='unidad',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='bodegaproductos',
            name='xvilla',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='total_villas',
            field=models.IntegerField(null=True),
        ),
    ]
